version: '2'
services:
   freeswitch:
     hostname: freeswitch
     container_name: freeswitch
     network_mode: "host"
     restart: always
     build: ./
    # image: wyliog/freeswitch
     command: freeswitch
     logging:
       options:
         max-size: 10m
     volumes:
      - ./conf:/etc/freeswitch
     tty: true
